name: E2E Automated Tests
run-name: 'Run e2e Tests'

on:
  push:
jobs:
  test:
      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.2.1
        - uses: actions/setup-node@v4
          with:
            node-version: 21
        - name: Install dependencies
          run: npm ci
        - name: Test
          run: |
            google-chrome --version
            echo ---------
            npx wdio run wdio.conf.js
